apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-postgres-svc
  namespace: {{.Values.namespace}}
spec:
  ports:
    - name: postgres
      port: 5432
  clusterIP: None
  selector:
    name: postgres
