apiVersion: v1
kind: Secret
metadata:
  name: postgres
stringData:
  PGUSER: postgres
  POSTGRES_USER: postgres
  REPLICATION_USER: replication
  REPLICATION_PASSWORD: replication
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  PGDATA: /data/pgdata
