include:
  - ./compose.logging.yaml
  - ./compose.dependency.yaml
services:
  cart-service:
    develop:
      watch:
        - path: ./internal/
          action: rebuild
        - path: ./cmd/
          action: rebuild
        - path: ./cart/
          action: rebuild
    build:
      context: .
    container_name: cart-service
    command: ["./ecommerce", "cart"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - logging
      - postgres
      - redis
      - ecommerce
    expose:
      - 8080
    ports:
      - 8080:8080
  notification-service:
    develop:
      watch:
        - path: ./internal/
          action: rebuild
        - path: ./cmd/
          action: rebuild
        - path: ./notification/
          action: rebuild
    build:
      context: .
    container_name: notification-service
    command: ["./ecommerce", "notification"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - logging
      - postgres
      - redis
      - ecommerce
    expose:
      - 8080
    ports:
      - 8081:8080
  order-service:
    develop:
      watch:
        - path: ./internal/
          action: rebuild
        - path: ./cmd/
          action: rebuild
        - path: ./order/
          action: rebuild
    build:
      context: .
    container_name: order-service
    command: ["./ecommerce", "order"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - logging
      - postgres
      - redis
      - ecommerce
    expose:
      - 8080
    ports:
      - 8082:8080
  product-service:
    develop:
      watch:
        - path: ./internal/
          action: rebuild
        - path: ./cmd/
          action: rebuild
        - path: ./product/
          action: rebuild
    build:
      context: .
    container_name: product-service
    command: ["./ecommerce", "product"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - logging
      - postgres
      - redis
      - ecommerce
    expose:
      - 8080
    ports:
      - 8083:8080
  user-service:
    develop:
      watch:
        - path: ./internal/
          action: rebuild
        - path: ./cmd/
          action: rebuild
        - path: ./user/
          action: rebuild
    build:
      context: .
    container_name: user-service
    command: ["./ecommerce", "user"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - logging
      - postgres
      - redis
      - ecommerce
    expose:
      - 8080
    ports:
      - 8084:8080
networks:
  ecommerce:
    name: ecommerce
