services:
  postgres:
    container_name: postgres
    image: postgres:16.6-alpine3.21
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - postgres
      - logging
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
  redis:
    container_name: redis
    image: redis/redis-stack:6.2.6-v17
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - redis
      - logging
    environment:
      REDIS_ARGS: "--user ${REDIS_USER} on +@all ~* >${REDIS_PASSWORD} --bind 0.0.0.0 --maxmemory-policy allkeys-lru"
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  nginx:
    container_name: nginx
    image: nginx:1.27.3-alpine-slim
    restart: always
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ecommerce
    ports:
      - 80:80
networks:
  postgres:
    name: postgres
  redis:
    name: redis
