services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - postgres
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s
  redis:
    container_name: redis
    image: redis:7.2.4-alpine3.19
    restart: always
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - ./infra/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
networks:
  postgres:
    name: postgres
  redis:
    name: redis
