include:
  - ./compose.logging.yaml
  - ./compose.dependency.yaml
services:
  cart-service:
    develop:
      watch:
        - path: ./internal/
          action: rebuild
        - path: ./cmd/
          action: rebuild
        - path: ./cart/
          action: rebuild
    build:
      context: .
    container_name: cart-service
    command: ["./ecommerce", "cart"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - logging
      - postgres
    ports:
      - 8080:8080
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-retries: 5
        loki-batch-size: 1000
  notification-service:
    develop:
      watch:
        - path: ./internal/
          action: rebuild
        - path: ./cmd/
          action: rebuild
        - path: ./notification/
          action: rebuild
    build:
      context: .
    container_name: notification-service
    command: ["./ecommerce", "notification"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - logging
      - postgres
    ports:
      - 8081:8080
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-retries: 5
        loki-batch-size: 1000
  order-service:
    develop:
      watch:
        - path: ./internal/
          action: rebuild
        - path: ./cmd/
          action: rebuild
        - path: ./order/
          action: rebuild
    build:
      context: .
    container_name: order-service
    command: ["./ecommerce", "order"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - logging
      - postgres
    ports:
      - 8082:8080
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-retries: 5
        loki-batch-size: 1000
  product-service:
    develop:
      watch:
        - path: ./internal/
          action: rebuild
        - path: ./cmd/
          action: rebuild
        - path: ./product/
          action: rebuild
    build:
      context: .
    container_name: product-service
    command: ["./ecommerce", "product"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - logging
      - postgres
    ports:
      - 8083:8080
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-retries: 5
        loki-batch-size: 1000
  shop-service:
    develop:
      watch:
        - path: ./internal/
          action: rebuild
        - path: ./cmd/
          action: rebuild
        - path: ./shop/
          action: rebuild
    build:
      context: .
    container_name: shop-service
    command: ["./ecommerce", "shop"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - logging
      - postgres
    ports:
      - 8084:8080
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-retries: 5
        loki-batch-size: 1000
  user-service:
    develop:
      watch:
        - path: ./internal/
          action: rebuild
        - path: ./cmd/
          action: rebuild
        - path: ./user/
          action: rebuild
    build:
      context: .
    container_name: user-service
    command: ["./ecommerce", "user"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - logging
      - postgres
    ports:
      - 8085:8080
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-retries: 5
        loki-batch-size: 1000
