// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteOrderItemFromOrdersById(ctx context.Context, id uuid.UUID) (OrderItem, error)
	FindOrderById(ctx context.Context, id uuid.UUID) (Order, error)
	FindOrderByIdAndUserId(ctx context.Context, arg FindOrderByIdAndUserIdParams) ([]Order, error)
	FindOrderByUserId(ctx context.Context, userID uuid.UUID) ([]Order, error)
	FindOrderItemById(ctx context.Context, id uuid.UUID) ([]OrderItem, error)
	FindOrderItemByIdAndUserId(ctx context.Context, arg FindOrderItemByIdAndUserIdParams) ([]OrderItem, error)
	InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error)
	InsertOrderItem(ctx context.Context, arg []InsertOrderItemParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
