// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteCartByIdAndUserId(ctx context.Context, arg DeleteCartByIdAndUserIdParams) (Cart, error)
	DeleteCartItemFromCartsById(ctx context.Context, arg DeleteCartItemFromCartsByIdParams) (CartItem, error)
	DeleteOrderItemFromOrdersById(ctx context.Context, id uuid.UUID) (OrderItem, error)
	DeleteProduct(ctx context.Context, id uuid.UUID) (Product, error)
	FindByEmail(ctx context.Context, email string) (User, error)
	FindById(ctx context.Context, id uuid.UUID) (User, error)
	FindCartById(ctx context.Context, arg FindCartByIdParams) (FindCartByIdRow, error)
	FindCartByUserId(ctx context.Context, id uuid.UUID) ([]FindCartByUserIdRow, error)
	FindCartItemByCartId(ctx context.Context, cartID uuid.UUID) ([]CartItem, error)
	FindCartItemById(ctx context.Context, id uuid.UUID) (CartItem, error)
	FindOrderById(ctx context.Context, arg FindOrderByIdParams) (FindOrderByIdRow, error)
	FindOrderByUserId(ctx context.Context, userID uuid.UUID) ([]Order, error)
	FindOrderItemById(ctx context.Context, id uuid.UUID) ([]OrderItem, error)
	FindOrderItemByIdAndUserId(ctx context.Context, arg FindOrderItemByIdAndUserIdParams) ([]OrderItem, error)
	FindOrderUserId(ctx context.Context, id uuid.UUID) ([]Order, error)
	FindProductById(ctx context.Context, id uuid.UUID) (Product, error)
	FindProductByIdLock(ctx context.Context, id uuid.UUID) (Product, error)
	FindProductByName(ctx context.Context, name string) (Product, error)
	FindProducts(ctx context.Context) ([]Product, error)
	FindProductsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Product, error)
	FindProductsByIdsLock(ctx context.Context, dollar_1 []uuid.UUID) ([]Product, error)
	GetOrders(ctx context.Context, dollar_1 []uuid.UUID) ([]GetOrdersRow, error)
	GetProducts(ctx context.Context) ([]Product, error)
	InsertCart(ctx context.Context, userID uuid.UUID) (Cart, error)
	InsertCartItem(ctx context.Context, arg InsertCartItemParams) (CartItem, error)
	InsertCartItems(ctx context.Context, arg []InsertCartItemsParams) (int64, error)
	InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error)
	InsertOrderItem(ctx context.Context, arg []InsertOrderItemParams) (int64, error)
	InsertOrders(ctx context.Context, arg []InsertOrdersParams) (int64, error)
	InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductQuantity(ctx context.Context, arg UpdateProductQuantityParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
