@base=http://localhost:8080/carts

# @name InsertCart
###
POST {{base}}/ HTTP/1.1
accept: application/json
content-type: application/json

{
  "userId": "6f15dd30-1fdf-4557-a4fb-edbe9654b9b9",
  "cartItems": [
    {
      "productId": "71fdec2c-d3d7-47ee-bfda-d9c9211bc7e7",
      "quantity": 3,
      "price": "12.345"
    }
  ]
}

# @name FindCartById
###
GET {{base}}/"" HTTP/1.1
accept: application/json
content-type: application/json

# @name FindCartByUserId
###
GET {{base}}?userId="" HTTP/1.1
accept: application/json
content-type: application/json


# @name FindCartByProductId
###
GET {{base}}?productId="" HTTP/1.1
accept: application/json
content-type: application/json
