@base=http://localhost:8080/carts
@token=a

# @name InsertCart
###
POST {{base}}/ HTTP/1.1
accept: application/json
content-type: application/json
Authorization: Bearer {{token}}

{
  "cartItems": [
    {
      "productId": "00495402-8426-492d-82a3-84ea577db197",
      "quantity": 3,
      "price": "12.345"
    }
  ]
}

# @name FindCartById
###
GET {{base}}/"" HTTP/1.1
accept: application/json
content-type: application/json
Authorization: Bearer {{token}}

# @name FindCartByUserId
###
GET {{base}}?userId="" HTTP/1.1
accept: application/json
content-type: application/json
Authorization: Bearer {{token}}


# @name FindCartByProductId
###
GET {{base}}?productId="" HTTP/1.1
accept: application/json
content-type: application/json
Authorization: Bearer {{token}}
