@base=http://localhost:8081/products

# @name InsertProduct
###
POST {{base}} HTTP/1.1
accept: application/json
content-type: application/json

{
  "name": "product 1",
  "price": "12345.100",
  "quantity": 100
}

# @name FindProducts
###
GET {{base}}?id="2ae2756f-08bd-4687-a6ee-24b3d9cd4a5a"&name="product 1" HTTP/1.1
accept: application/json
