@base=http://localhost:8080/users

# @name register
###
POST {{base}}/register HTTP/1.1
accept: application/json
content-type: application/json

{
  "email": "user@test.com",
  "username": "user1",
  "password": "password"
}


# @name login
### login
POST {{base}}/login HTTP/1.1
accept: application/json
content-type: application/json

{
  "email": "user@test.com",
  "password": "password"
}

