global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888", "otel-collector:8889"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: "redis_exporter_targets"
    static_configs:
      - targets: [redis://redis:6379]
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121
  ## config for scraping the exporter itself
  - job_name: "redis_exporter"
    static_configs:
      - targets: [redis-exporter:9121]
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]
  - job_name: "postgres-exporter"
    static_configs:
      - targets: [postgres-exporter:9187]
