// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	FindByEmail(ctx context.Context, email string) (User, error)
	FindById(ctx context.Context, id uuid.UUID) (User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
