apiVersion: apps/v1
kind: Service
metadata:
  name: product
  namespace: {{.Values.namespace}}
  labels:
    name: product
spec:
  ports:
    - name: product
      port: 80
  selector:
    name: product
