// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForInsertCartItem implements pgx.CopyFromSource.
type iteratorForInsertCartItem struct {
	rows                 []InsertCartItemParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertCartItem) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertCartItem) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CartID,
		r.rows[0].ProductID,
		r.rows[0].Quantity,
		r.rows[0].Price,
	}, nil
}

func (r iteratorForInsertCartItem) Err() error {
	return nil
}

func (q *Queries) InsertCartItem(ctx context.Context, arg []InsertCartItemParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"cart_items"}, []string{"cart_id", "product_id", "quantity", "price"}, &iteratorForInsertCartItem{rows: arg})
}
