// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	UserID    uuid.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type CartItem struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	CartID    uuid.UUID        `db:"cart_id" json:"cart_id"`
	ProductID uuid.UUID        `db:"product_id" json:"product_id"`
	Quantity  int32            `db:"quantity" json:"quantity"`
	Price     pgtype.Numeric   `db:"price" json:"price"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
