// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteCartItemFromCartsById(ctx context.Context, arg DeleteCartItemFromCartsByIdParams) (CartItem, error)
	FindCartById(ctx context.Context, id uuid.UUID) (Cart, error)
	FindCartByUserId(ctx context.Context, userID uuid.UUID) ([]Cart, error)
	FindCartItemById(ctx context.Context, id uuid.UUID) (CartItem, error)
	InsertCart(ctx context.Context, userID uuid.UUID) (Cart, error)
	InsertCartItem(ctx context.Context, arg []InsertCartItemParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
