// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteCartByIdAndUserId(ctx context.Context, arg DeleteCartByIdAndUserIdParams) (Cart, error)
	DeleteCartItemFromCartsById(ctx context.Context, arg DeleteCartItemFromCartsByIdParams) (CartItem, error)
	FindCartById(ctx context.Context, arg FindCartByIdParams) (FindCartByIdRow, error)
	FindCartByUserId(ctx context.Context, id uuid.UUID) ([]FindCartByUserIdRow, error)
	FindCartItemByCartId(ctx context.Context, cartID uuid.UUID) ([]CartItem, error)
	FindCartItemById(ctx context.Context, id uuid.UUID) (CartItem, error)
	InsertCart(ctx context.Context, userID uuid.UUID) (Cart, error)
	InsertCartItem(ctx context.Context, arg InsertCartItemParams) (CartItem, error)
	InsertCartItems(ctx context.Context, arg []InsertCartItemsParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
